### ISSUE TITLE
Missing "compat/curl-for-windows"

### ISSUE THREAD

**Issue by iwearsable** [Ravencoin-Miner/Ravencoin#2]
While attempting to compile I got an error about line 600 in api.cpp 
`#include "compat/curl-for-windows/openssl/openssl/crypto/sha/sha.h"`

It appears that it is looking for a file or files in the curl-for-windows directory which does not exist. I was able to copy this from another project and it then compiled without issue.

**Comment by Ravencoin-Miner** [comment]
Thank you, I will make sure this is uploaded to the source directory.
Done!
